# Generated by Django 4.2.2 on 2023-06-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('shop_name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=32)),
            ],
        ),
    ]
